[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
neobank = "2aqMXRCKoxXC9tw42p6AfQuKjsdJfG1bVvtMZ8xwoNqG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
